name: Deploy ASP app to Azure Web App - MockIAV

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: IAVtest

    steps:
      - uses: actions/checkout@v4

      - name: Set up deployment files
        run: |
          mkdir "${{ github.workspace }}\deploy"
          cp -r . "${{ github.workspace }}\deploy"


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'stress-bot'
          slot-name: 'Production'
          package: ${{ github.workspace }}\deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2A18407396B74796A7D0DDE67C0EC121 }}


          